services:

  node-app:
    container_name: devops-node-app

    build:
        context: ./app

    ports:
        - "3000:3000"

    volumes:
        - ./app:/app
        - /app/node_modules
        

    env_file:
        - .env 

    environment:
        - MONGO_URL=mongodb://mongo:27017/todos
        
    depends_on:
      - mongo

    command: npm run dev

  mongo:
    image: mongo:7
    container_name: mongo-db
    restart: always

    ports:
      - "27017:27017"

    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:

      
