services:

  node-app:
    container_name: devops-node-app

    build:
        context: ./app
        dockerfile: Dockerfile.dev

    ports:
        - "3000:3000"

    volumes:
        - ./app:/app
        - /app/node_modules
        

    env_file:
        - .env
        
    depends_on:
      - mongo

    command: npm run dev

  mongo:
    image: mongo:7
    container_name: mongo-db
    restart: always

    ports:
      - "27017:27017"

    volumes:
      - mongo-data:/data/db

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/alerts.yml:/etc/prometheus/alerts.yml
    
    depends_on:
      - node-app

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    depends_on:
      - prometheus
    volumes:
      - grafana-data:/var/lib/grafana

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /dev/disk:/dev/disk:ro
    privileged: true
    devices:
      - /dev/kmsg

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml

    env_file:
    - .env

volumes:
  mongo-data:
  grafana-data:

      
